root: ./
​
structure:
  readme: README.md
  summary: SUMMARY.md
​
redirects:
  chapter/products: products.md
  gettingstarted/introduction.md
  gettingstarted/connection/README.md
  gettingstarted/connection/lopy.md
  gettingstarted/connection/lopy4.md
  gettingstarted/connection/sipy.md
  gettingstarted/connection/gpy.md
  gettingstarted/connection/fipy.md
  gettingstarted/connection/wipy.md
  gettingstarted/installation/README.md
  gettingstarted/installation/drivers.md
  gettingstarted/installation/firmwaretool.md
  gettingstarted/installation/pymakr.md
  gettingstarted/programming/README.md
  gettingstarted/programming/micropython.md
  gettingstarted/programming/examples.md
  gettingstarted/programming/first-project.md
  gettingstarted/programming/repl/README.md
  gettingstarted/programming/repl/serial.md
  gettingstarted/programming/repl/telnet.md
  gettingstarted/programming/ftp.md
  gettingstarted/programming/safeboot.md
  gettingstarted/registration/README.md
  gettingstarted/registration/sigfox.md
  gettingstarted/registration/cellular.md
  gettingstarted/registration/lora/README.md
  gettingstarted/registration/lora/ttn.md
  gettingstarted/registration/lora/objenious.md
  Installation](pymakr/installation/README.md
  pymakr/installation/atom.md
  pymakr/installation/vscode.md
  pymakr/toolsfeatures.md
  pymakr/settings.md
  pytrackpysense/introduction.md
  pytrackpysense/installation/README.md
  pytrackpysense/installation/firmware.md
  pytrackpysense/installation/drivers.md
  pytrackpysense/installation/libraries.md
  pytrackpysense/apireference/README.md
  pytrackpysense/apireference/pytrack.md
  pytrackpysense/apireference/pysense.md
  pytrackpysense/apireference/pyscan.md
  pytrackpysense/apireference/sleep.md
  tutorials/introduction.md
  tutorials/all/README.md
  tutorials/all/repl.md
  tutorials/all/wlan.md
  tutorials/all/ble.md
  tutorials/all/https.md
  tutorials/all/mqtt.md
  tutorials/all/aws.md
  tutorials/all/adc.md
  tutorials/all/i2c.md
  tutorials/all/owd.md
  tutorials/all/threading.md
  tutorials/all/rgbled.md
  tutorials/all/timers.md
  tutorials/all/pir.md
  tutorials/all/modbus.md
  tutorials/all/ota.md
  tutorials/all/rmt.md
  tutorials/all/socket.md
  tutorials/lora/README.md
  tutorials/lora/lora-mac.md
  tutorials/lora/lorawan-otaa.md
  tutorials/lora/lorawan-abp.md
  tutorials/lora/lora-mac-nano-gateway.md
  tutorials/lora/module-module.md
  tutorials/lora/lorawan-nano-gateway.md
  tutorials/lora/rn2483-to-lopy.md
  tutorials/lora/lora-mesh.md
  tutorials/sigfox.md
  tutorials/lte/README.md
  tutorials/lte/cat-m1.md
  tutorials/lte/nb-iot.md
  tutorials/lte/imei.md
  tutorials/lte/firmware.md
  tutorials/pytrack.md
  tutorials/pysense.md
  tutorials/pyscan.md
  firmwareapi/introduction.md
  firmwareapi/pycom/README.md
  firmwareapi/pycom/machine/README.md
  firmwareapi/pycom/machine/adc.md
  firmwareapi/pycom/machine/dac.md
  firmwareapi/pycom/machine/i2c.md
  firmwareapi/pycom/machine/pin.md
  firmwareapi/pycom/machine/pwm.md
  firmwareapi/pycom/machine/rtc.md
  firmwareapi/pycom/machine/spi.md
  firmwareapi/pycom/machine/uart.md
  firmwareapi/pycom/machine/wdt.md
  firmwareapi/pycom/machine/timer.md
  firmwareapi/pycom/machine/sd.md
  firmwareapi/pycom/machine/can.md
  firmwareapi/pycom/machine/rmt.md
  firmwareapi/pycom/network/README.md
  firmwareapi/pycom/network/wlan.md
  firmwareapi/pycom/network/server.md
  firmwareapi/pycom/network/bluetooth/README.md
  firmwareapi/pycom/network/bluetooth/gatt.md
  firmwareapi/pycom/network/bluetooth/gattcconnection.md
  firmwareapi/pycom/network/bluetooth/gattccservice.md
  firmwareapi/pycom/network/bluetooth/gattccharacteristic.md
  firmwareapi/pycom/network/bluetooth/gattsservice.md
  firmwareapi/pycom/network/bluetooth/gattscharacteristic.md
  firmwareapi/pycom/network/lora.md
  firmwareapi/pycom/network/sigfox.md
  firmwareapi/pycom/network/lte.md
  firmwareapi/pycom/aes.md
  firmwareapi/pycom/pycom.md
  firmwareapi/micropython/README.md
  firmwareapi/micropython/micropython.md
  firmwareapi/micropython/uctypes.md
  firmwareapi/micropython/sys.md
  firmwareapi/micropython/uos.md
  firmwareapi/micropython/array.md
  firmwareapi/micropython/cmath.md
  firmwareapi/micropython/math.md
  firmwareapi/micropython/gc.md
  firmwareapi/micropython/ubinascii.md
  firmwareapi/micropython/ujson.md
  firmwareapi/micropython/ure.md
  firmwareapi/micropython/usocket.md
  firmwareapi/micropython/select.md
  firmwareapi/micropython/utime.md
  firmwareapi/micropython/uhashlib.md
  firmwareapi/micropython/ussl.md
  firmwareapi/micropython/ucrypto.md
  firmwareapi/micropython/ustruct/README.md
  firmwareapi/micropython/ustruct/uzlib.md
  firmwareapi/micropython/_thread.md
  firmwareapi/micropython/builtin.md
  firmwareapi/notes.md
  datasheets/introduction.md
  datasheets/development/README.md
  datasheets/development/wipy2.md
  datasheets/development/wipy3.md
  datasheets/development/lopy.md
  datasheets/development/lopy4.md
  datasheets/development/sipy.md
  datasheets/development/gpy.md
  datasheets/development/fipy.md
  datasheets/oem/README.md
  datasheets/oem/w01.md
  datasheets/oem/l01.md
  datasheets/oem/l04.md
  datasheets/oem/g01.md
  datasheets/oem/l01_reference.md
  datasheets/oem/universal_reference.md
  datasheets/boards/README.md
  datasheets/boards/expansion3.md
  datasheets/boards/pytrack.md
  datasheets/boards/pysense.md
  datasheets/boards/pyscan.md
  datasheets/boards/expansion2.md
  datasheets/boards/deepsleep/README.md
  datasheets/boards/deepsleep/api.md
  datasheets/notes.md
  pybytes/introduction.md
  pybytes/getstarted.md
  pybytes/connect/README.md
  pybytes/connect/quick.md
  pybytes/connect/flash.md
  pybytes/connect/sigfox/README.md
  pybytes/connect/sigfox/devkit.md
  pybytes/connect/sigfox/custom.md
  pybytes/dashboard.md
  docnotes/introduction.md
  docnotes/syntax.md
  docnotes/replscript.md
  docnotes/mesh-networks.md
  advance/downgrade.md
  advance/cli.md
  advance/encryption.md
