root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  chapter/products: ./products

  chapter/gettingstarted: ./gettingstarted/introduction
  chapter/gettingstarted/introduction: ./gettingstarted/introduction
  chapter/gettingstarted/hardwaresetup: ./gettingstarted/connection/README
  chapter/gettingstarted/connection/lopy: ./gettingstarted/connection/lopy
  chapter/gettingstarted/connection/lopy4: ./gettingstarted/connection/lopy4
  chapter/gettingstarted/connection/sipy: ./gettingstarted/connection/sipy
  chapter/gettingstarted/connection/gpy: ./gettingstarted/connection/gpy
  chapter/gettingstarted/connection/fipy: ./gettingstarted/connection/fipy
  chapter/gettingstarted/connection/wipy: ./gettingstarted/connection/wipy
  chapter/gettingstarted/installation/installingsoftware: ./gettingstarted/installation/README
  chapter/gettingstarted/installation/drivers: ./gettingstarted/installation/drivers
  chapter/gettingstarted/installation/firmwaretool: ./gettingstarted/installation/firmwaretool
  chapter/gettingstarted/installation/pymakr: ./gettingstarted/installation/pymakr
  chapter/gettingstarted/programming: ./gettingstarted/programming/README
  chapter/gettingstarted/programming/micropython: ./gettingstarted/programming/micropython
  chapter/gettingstarted/programming/examples: ./gettingstarted/programming/examples
  chapter/gettingstarted/programming/first-project: ./gettingstarted/programming/first-project
  chapter/gettingstarted/programming/repl: ./gettingstarted/programming/repl/README
  chapter/gettingstarted/programming/repl/serial: ./gettingstarted/programming/repl/serial
  chapter/gettingstarted/programming/repl/telnet: ./gettingstarted/programming/repl/telnet
  chapter/gettingstarted/programming/ftp: ./gettingstarted/programming/ftp
  chapter/gettingstarted/programming/safeboot: ./gettingstarted/programming/safeboot
  chapter/gettingstarted/registration/README: ./gettingstarted/registration/README
  chapter/gettingstarted/registration/sigfox: ./gettingstarted/registration/sigfox
  chapter/gettingstarted/registration/cellular: ./gettingstarted/registration/cellular
  chapter/gettingstarted/registration/lora: ./gettingstarted/registration/lora/README
  chapter/gettingstarted/registration/lora/ttn: ./gettingstarted/registration/lora/ttn
  chapter/gettingstarted/registration/lora/objenious: ./gettingstarted/registration/lora/objenious

  chapter/pymakr/installation: ./pymakr/installation/README
  chapter/pymakr/installation/atom: ./pymakr/installation/atom
  chapter/pymakr/installation/vscode: ./pymakr/installation/vscode
  chapter/pymakr/toolsfeatures: ./pymakr/toolsfeatures
  chapter/pymakr/settings: ./pymakr/settings

  chapter/pytrackpysense: ./pytrackpysense/introduction
  chapter/pytrackpysense/installation: ./pytrackpysense/installation/README
  chapter/pytrackpysense/installation/firmware: ./pytrackpysense/installation/firmware
  chapter/pytrackpysense/installation/drivers: ./pytrackpysense/installation/drivers
  chapter/pytrackpysense/installation/libraries: ./pytrackpysense/installation/libraries
  chapter/pytrackpysense/apireference: ./pytrackpysense/apireference/README
  chapter/pytrackpysense/apireference/pytrack: ./pytrackpysense/apireference/pytrack
  chapter/pytrackpysense/apireference/pysense: ./pytrackpysense/apireference/pysense
  chapter/pytrackpysense/apireference/pyscan: ./pytrackpysense/apireference/pyscan
  chapter/pytrackpysense/apireference/sleep: ./pytrackpysense/apireference/sleep

  chapter/tutorials: ./tutorials/introduction
  chapter/tutorials/all: ./tutorials/all/README
  chapter/tutorials/all/repl: ./tutorials/all/repl
  chapter/tutorials/all/wlan: ./tutorials/all/wlan
  chapter/tutorials/all/ble: ./tutorials/all/ble
  chapter/tutorials/all/https: ./tutorials/all/https
  chapter/tutorials/all/mqtt: ./tutorials/all/mqtt
  chapter/tutorials/all/aws: ./tutorials/all/aws
  chapter/tutorials/all/adc: ./tutorials/all/adc
  chapter/tutorials/all/i2c: ./tutorials/all/i2c
  chapter/tutorials/all/owd: ./tutorials/all/owd
  chapter/tutorials/all/threading: ./tutorials/all/threading
  chapter/tutorials/all/rgbled: ./tutorials/all/rgbled
  chapter/tutorials/all/timers: ./tutorials/all/timers
  chapter/tutorials/all/pir: ./tutorials/all/pir
  chapter/tutorials/all/modbus: ./tutorials/all/modbus
  chapter/tutorials/all/ota: ./tutorials/all/ota
  chapter/tutorials/all/rmt: ./tutorials/all/rmt
  chapter/tutorials/all/socket: ./tutorials/all/socket
  chapter/tutorials/lora: ./tutorials/lora/README
  chapter/tutorials/lora/lora-mac: ./tutorials/lora/lora-mac
  chapter/tutorials/lora/lorawan-otaa: ./tutorials/lora/lorawan-otaa
  chapter/tutorials/lora/lorawan-abp: ./tutorials/lora/lorawan-abp
  chapter/tutorials/lora/lora-mac-nano-gateway: ./tutorials/lora/lora-mac-nano-gateway
  chapter/tutorials/lora/module-module: ./tutorials/lora/module-module
  chapter/tutorials/lora/lorawan-nano-gateway: ./tutorials/lora/lorawan-nano-gateway
  chapter/tutorials/lora/rn2483-to-lopy: ./tutorials/lora/rn2483-to-lopy
  chapter/tutorials/lora/lora-mesh: ./tutorials/lora/lora-mesh
  chapter/tutorials/sigfox: ./tutorials/sigfox
  chapter/tutorials/lte: ./tutorials/lte/README
  chapter/tutorials/lte/cat-m1: ./tutorials/lte/cat-m1
  chapter/tutorials/lte/nb-iot: ./tutorials/lte/nb-iot
  chapter/tutorials/lte/imei: ./tutorials/lte/imei
  chapter/tutorials/lte/firmware: ./tutorials/lte/firmware
  chapter/tutorials/pytrack: ./tutorials/pytrack
  chapter/tutorials/pysense: ./tutorials/pysense
  chapter/tutorials/pyscan: ./tutorials/pyscan

  chapter/firmwareapi: ./firmwareapi/introduction
  chapter/firmwareapi/pycom: ./firmwareapi/pycom/README
  chapter/firmwareapi/pycom/machine: ./firmwareapi/pycom/machine/README
  chapter/firmwareapi/pycom/machine/adc: ./firmwareapi/pycom/machine/adc
  chapter/firmwareapi/pycom/machine/dac: ./firmwareapi/pycom/machine/dac
  chapter/firmwareapi/pycom/machine/i2c: ./firmwareapi/pycom/machine/i2c
  chapter/firmwareapi/pycom/machine/pin: ./firmwareapi/pycom/machine/pin
  chapter/firmwareapi/pycom/machine/pwm: ./firmwareapi/pycom/machine/pwm
  chapter/firmwareapi/pycom/machine/rtc: ./firmwareapi/pycom/machine/rtc
  chapter/firmwareapi/pycom/machine/spi: ./firmwareapi/pycom/machine/spi
  chapter/firmwareapi/pycom/machine/uart: ./firmwareapi/pycom/machine/uart
  chapter/firmwareapi/pycom/machine/wdt: ./firmwareapi/pycom/machine/wdt
  chapter/firmwareapi/pycom/machine/timer: ./firmwareapi/pycom/machine/timer
  chapter/firmwareapi/pycom/machine/sd: ./firmwareapi/pycom/machine/sd
  chapter/firmwareapi/pycom/machine/can: ./firmwareapi/pycom/machine/can
  chapter/firmwareapi/pycom/machine/rmt: ./firmwareapi/pycom/machine/rmt
  chapter/firmwareapi/pycom/network: ./firmwareapi/pycom/network/README
  chapter/firmwareapi/pycom/network/wlan: ./firmwareapi/pycom/network/wlan
  chapter/firmwareapi/pycom/network/server: ./firmwareapi/pycom/network/server
  chapter/firmwareapi/pycom/network/bluetooth: ./firmwareapi/pycom/network/bluetooth/README
  chapter/firmwareapi/pycom/network/bluetooth/gatt: ./firmwareapi/pycom/network/bluetooth/gatt
  firmwareapi/pycom/network/bluetooth/gattcconnection: chapter/./firmwareapi/pycom/network/bluetooth/gattcconnection
  firmwareapi/pycom/network/bluetooth/gattccservice: chapter/./firmwareapi/pycom/network/bluetooth/gattccservice
  firmwareapi/pycom/network/bluetooth/gattccharacteristic: chapter/./firmwareapi/pycom/network/bluetooth/gattccharacteristic
  chapter/firmwareapi/pycom/network/bluetooth/gattsservice: ./firmwareapi/pycom/network/bluetooth/gattsservice
  firmwareapi/pycom/network/bluetooth/gattscharacteristic: chapter/./firmwareapi/pycom/network/bluetooth/gattscharacteristic
  chapter/firmwareapi/pycom/network/lora: ./firmwareapi/pycom/network/lora
  chapter/firmwareapi/pycom/network/sigfox: ./firmwareapi/pycom/network/sigfox
  chapter/firmwareapi/pycom/network/lte: ./firmwareapi/pycom/network/lte
  chapter/firmwareapi/pycom/aes: ./firmwareapi/pycom/aes
  chapter/firmwareapi/pycom/pycom: ./firmwareapi/pycom/pycom
  chapter/firmwareapi/micropython: ./firmwareapi/micropython/README
  chapter/firmwareapi/micropython/micropython: ./firmwareapi/micropython/micropython
  chapter/firmwareapi/micropython/uctypes: ./firmwareapi/micropython/uctypes
  chapter/firmwareapi/micropython/sys: ./firmwareapi/micropython/sys
  chapter/firmwareapi/micropython/uos: ./firmwareapi/micropython/uos
  chapter/firmwareapi/micropython/array: ./firmwareapi/micropython/array
  chapter/firmwareapi/micropython/cmath: ./firmwareapi/micropython/cmath
  chapter/firmwareapi/micropython/math: ./firmwareapi/micropython/math
  chapter/firmwareapi/micropython/gc: ./firmwareapi/micropython/gc
  chapter/firmwareapi/micropython/ubinascii: ./firmwareapi/micropython/ubinascii
  chapter/firmwareapi/micropython/ujson: ./firmwareapi/micropython/ujson
  chapter/firmwareapi/micropython/ure: ./firmwareapi/micropython/ure
  chapter/firmwareapi/micropython/usocket: ./firmwareapi/micropython/usocket
  chapter/firmwareapi/micropython/select: ./firmwareapi/micropython/select
  chapter/firmwareapi/micropython/utime: ./firmwareapi/micropython/utime
  chapter/firmwareapi/micropython/uhashlib: ./firmwareapi/micropython/uhashlib
  chapter/firmwareapi/micropython/ussl: ./firmwareapi/micropython/ussl
  chapter/firmwareapi/micropython/ucrypto: ./firmwareapi/micropython/ucrypto
  chapter/firmwareapi/micropython/ustruct: ./firmwareapi/micropython/ustruct
  chapter/firmwareapi/micropython/uzlib: ./firmwareapi/micropython/uzlib
  chapter/firmwareapi/micropython/_thread: ./firmwareapi/micropython/_thread
  chapter/firmwareapi/micropython/builtin: ./firmwareapi/micropython/builtin
  chapter/firmwareapi/notes: ./firmwareapi/notes

  chapter/datasheets: ./datasheets/introduction
  chapter/datasheets/development: ./datasheets/development/README
  chapter/datasheets/development/wipy2: ./datasheets/development/wipy2
  chapter/datasheets/development/wipy3: ./datasheets/development/wipy3
  chapter/datasheets/development/lopy: ./datasheets/development/lopy
  chapter/datasheets/development/lopy4: ./datasheets/development/lopy4
  chapter/datasheets/development/sipy: ./datasheets/development/sipy
  chapter/datasheets/development/gpy: ./datasheets/development/gpy
  chapter/datasheets/development/fipy: ./datasheets/development/fipy
  chapter/datasheets/oem: ./datasheets/oem/README
  chapter/datasheets/oem/w01: ./datasheets/oem/w01
  chapter/datasheets/oem/l01: ./datasheets/oem/l01
  chapter/datasheets/oem/l04: ./datasheets/oem/l04
  chapter/datasheets/oem/g01: ./datasheets/oem/g01
  chapter/datasheets/oem/l01_reference: ./datasheets/oem/l01_reference
  chapter/datasheets/oem/universal_reference: ./datasheets/oem/universal_reference
  chapter/datasheets/boards: ./datasheets/boards/README
  chapter/datasheets/boards/expansion3: ./datasheets/boards/expansion3
  chapter/datasheets/boards/pytrack: ./datasheets/boards/pytrack
  chapter/datasheets/boards/pysense: ./datasheets/boards/pysense
  chapter/datasheets/boards/pyscan: ./datasheets/boards/pyscan
  chapter/datasheets/boards/expansion2: ./datasheets/boards/expansion2
  chapter/datasheets/boards/deepsleep: ./datasheets/boards/deepsleep/README
  chapter/datasheets/boards/deepsleep/api: ./datasheets/boards/deepsleep/api
  chapter/datasheets/notes: ./datasheets/notes

  chapter/pybytes: ./pybytes/introduction
  chapter/pybytes/getstarted/intro: ./pybytes/getstarted
  chapter/pybytes/connect/intro: ./pybytes/connect/README
  chapter/pybytes/connect/quick: ./pybytes/connect/quick
  chapter/pybytes/connect/flash: ./pybytes/connect/flash
  chapter/pybytes/connect/sigfox/sigfox: ./pybytes/connect/sigfox/README
  chapter/pybytes/connect/sigfox/sigfoxDevKit: ./pybytes/connect/sigfox/devkit
  chapter/pybytes/connect/sigfox/sigfoxCustomContract: ./pybytes/connect/sigfox/custom
  chapter/pybytes/dashboard/intro: ./pybytes/dashboard

  chapter/docnotes: ./docnotes/introduction
  chapter/docnotes/syntax: ./docnotes/syntax
  chapter/docnotes/replscript: ./docnotes/replscript
  chapter/docnotes/mesh-networks: ./docnotes/mesh-networks

  chapter/advance/downgrade: ./advance/downgrade
  chapter/advance/cli: ./advance/cli
  chapter/advance/encryption: ./advance/encryption

  chapter/license: ./license.md
